x=input('enter first number:')
y=input('enter second number:')
print(('x > y  is',x>y))
print(('x < y  is',x<y))
print(('x >= y  is',x>=y))
print(('x <= y  is',x<=y))
print(('x == y  is',x==y))
print(('x != y  is',x!=y))
print(('x > y  is',x>y))